### ISSUE TITLE
Sycning

### ISSUE THREAD

**Issue by BWBellairs** [devzero-xyz/Andromeda#36]
Andromeda's syncing takes too long. I'm thinking of making it a separate thread on connecting to a server and have commands run as normal. One issue with this is that plugins run with irc.state and suchlike may not be provided with not enough data until syncing is complete.

**Comment by itslukej** [comment]
*Syncing

**Comment by BWBellairs** [comment]
eh, It's the amount of data that's received from the server that's stopping Andromeda during the syncing peroid, I'm gonna close this issue
